import type { Product } from "./cart-context"

export const products: Product[] = [
  {
    id: 1,
    name: "Wireless Headphones",
    price: 2999,
    image: "/wireless-headphones-black-modern.jpg",
    category: "Audio",
    description: "High-quality wireless headphones with noise cancellation and 30-hour battery life.",
  },
  {
    id: 2,
    name: "Smart Watch Pro",
    price: 4999,
    image: "/smart-watch-fitness-tracker.jpg",
    category: "Wearables",
    description: "Advanced smartwatch with health tracking, GPS, and water resistance.",
  },
  {
    id: 3,
    name: "Mechanical Keyboard",
    price: 3499,
    image: "/mechanical-gaming-keyboard-rgb.jpg",
    category: "Accessories",
    description: "RGB mechanical keyboard with Cherry MX switches for gaming and typing.",
  },
  {
    id: 4,
    name: "Portable Charger",
    price: 1499,
    image: "/portable-power-bank-charger.jpg",
    category: "Accessories",
    description: "20000mAh portable charger with fast charging support.",
  },
  {
    id: 5,
    name: "Wireless Mouse",
    price: 1999,
    image: "/wireless-ergonomic-mouse.jpg",
    category: "Accessories",
    description: "Ergonomic wireless mouse with precision tracking and long battery life.",
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    price: 2499,
    image: "/bluetooth-speaker-portable.jpg",
    category: "Audio",
    description: "Portable Bluetooth speaker with 360-degree sound and waterproof design.",
  },
  {
    id: 7,
    name: "4K Webcam",
    price: 5999,
    image: "/4k-webcam-hd.jpg",
    category: "Accessories",
    description: "Professional 4K webcam with auto-focus and built-in microphone.",
  },
  {
    id: 8,
    name: "USB-C Hub",
    price: 2199,
    image: "/usb-c-hub-multiport.jpg",
    category: "Accessories",
    description: "7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader.",
  },
  {
    id: 9,
    name: "Wireless Charger",
    price: 1299,
    image: "/wireless-charger-pad.jpg",
    category: "Accessories",
    description: "Fast wireless charging pad compatible with all Qi-enabled devices.",
  },
  {
    id: 10,
    name: "Noise Cancelling Earbuds",
    price: 3899,
    image: "/noise-cancelling-earbuds.jpg",
    category: "Audio",
    description: "True wireless earbuds with active noise cancellation and 8-hour battery.",
  },
  {
    id: 11,
    name: "Monitor Stand",
    price: 1599,
    image: "/monitor-stand-adjustable.jpg",
    category: "Accessories",
    description: "Adjustable monitor stand with storage drawer and ergonomic design.",
  },
  {
    id: 12,
    name: "External SSD",
    price: 4499,
    image: "/external-ssd-fast.jpg",
    category: "Storage",
    description: "1TB portable SSD with 1000MB/s read speed and USB-C connectivity.",
  },
  {
    id: 13,
    name: "Gaming Mousepad",
    price: 999,
    image: "/gaming-mousepad-large.jpg",
    category: "Accessories",
    description: "Large RGB gaming mousepad with non-slip base and durable surface.",
  },
  {
    id: 14,
    name: "Laptop Stand",
    price: 1899,
    image: "/laptop-stand-aluminum.jpg",
    category: "Accessories",
    description: "Aluminum laptop stand with adjustable height and cooling design.",
  },
  {
    id: 15,
    name: "Mechanical Switches",
    price: 899,
    image: "/mechanical-switches-pack.jpg",
    category: "Accessories",
    description: "Pack of 110 mechanical keyboard switches with various actuation options.",
  },
  {
    id: 16,
    name: "Cable Organizer",
    price: 499,
    image: "/cable-organizer-set.jpg",
    category: "Accessories",
    description: "Set of cable organizers and clips for neat desk management.",
  },
  {
    id: 17,
    name: "Desk Lamp LED",
    price: 2299,
    image: "/desk-lamp-led.jpg",
    category: "Lighting",
    description: "Adjustable LED desk lamp with USB charging port and 5 brightness levels.",
  },
  {
    id: 18,
    name: "Phone Holder",
    price: 599,
    image: "/phone-holder-stand.jpg",
    category: "Accessories",
    description: "Adjustable phone holder with strong grip and foldable design.",
  },
]
